baseurl = "https://dhcu.ca/"
title = "dhcu.ca"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "blue"
  description = "DIGH5000 @ Carleton U, 2017-18"
  copyright = "You can find me in person in PA406 or the Library Starbucks <br><br>"
  sidebarAbout = [
    "A graduate seminar in the digital humanities, asking:",
    "<i>What should undergrads know about DH?</i>",
    "Your mission: to write <b>the</b> book.",
    "Caveat Lector: All readings listed are mere <i>possibilities</i> and do not necessarily represent <i>canon</i>. Let them be the starting point for your explorations.",
    "Carleton University<br> DIGH5000, 2017-2018"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "shawn.graham@carleton.ca"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = ""

  [[params.navlinks]]
  name = "Syllabus"
  url = "portfolio/syllabus/"

  [[params.navlinks]]
  name = "Tutorials"
  url = "portfolio/tutorials/"

  [[params.navlinks]]
  name = "Shawn Graham"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [params.social]
  # facebook      = "full page or profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  email         = "shawn.graham@carleton.ca"
  twitter       = "http://twitter.com/electricarchaeo"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  # instagram     = "full profile url in instagram"
  github        = "https://github.com/shawngraham"
